// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACWHHH5oa_qKgG28BOd6zsWcQ2iG4ERL8',
    appId: '1:661463143449:web:87ae8e4ee26f761dad4688',
    messagingSenderId: '661463143449',
    projectId: 'intellihome-2026',
    authDomain: 'intellihome-2026.firebaseapp.com',
    storageBucket: 'intellihome-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxOPX8DNhF8NfYLklfxcXa1jlkYhWO1zM',
    appId: '1:661463143449:android:86c2e73ea9c1dd11ad4688',
    messagingSenderId: '661463143449',
    projectId: 'intellihome-2026',
    storageBucket: 'intellihome-2026.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACWHHH5oa_qKgG28BOd6zsWcQ2iG4ERL8',
    appId: '1:661463143449:web:8a17b49a2775be50ad4688',
    messagingSenderId: '661463143449',
    projectId: 'intellihome-2026',
    authDomain: 'intellihome-2026.firebaseapp.com',
    storageBucket: 'intellihome-2026.firebasestorage.app',
  );
}
